### ISSUE TITLE
virt-dib: error: libguestfs error: mkmountpoint: /tmp/in_target.aux: No  such file or directory

### ISSUE THREAD

**Issue by guoqiao** [openstack-charmers/octavia-diskimage-retrofit#15]
I am on Ubutu 18.04.

tool installed with devmode:

    sudo snap install --edge --devmode octavia-diskimage-retrofit

run tool as root and in required dir:

    root@t480:/var/snap/octavia-diskimage-retrofit/common# 
    octavia-diskimage-retrofit ubuntu-18.04.2-server-amd64.iso ubuntu-amphora-haproxy-amd64.qcow2

failed with error:

>virt-dib: error: libguestfs error: mkmountpoint: /tmp/in_target.aux: No such file or directory

Full debug log attached: [octavia-diskimage-retrofit.log](https://github.com/openstack-charmers/octavia-diskimage-retrofit/files/3987957/octavia-diskimage-retrofit.log)

**Comment by fnordahl** [comment]
The tool is meant to be used with an [Ubuntu Cloud Image](https://cloud-images.ubuntu.com/) in a format that `qemu-img` convert can understand (typically `qcow2` or `raw`).

It appears you are attempting to run it on a standard Ubuntu Server ISO (CD-ROM) image.
